name: CI-CD Pipeline

on:
  push:
    branches:
      - development
      - main

env:
  IMAGE_NAME: gem-app
  CONTAINER_NAME: gem-container

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/development'
    runs-on: self-hosted
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build JAR
        run: |
          docker run --rm -v ${PWD}:/app -w /app maven:3.9.6-eclipse-temurin-21 mvn clean package

      - name: Build Docker Image
        run: docker build -t gem:dev .

      - name: Stop Old Container
        continue-on-error: true
        run: docker stop ${env:CONTAINER_NAME}-dev

      - name: Remove Old Container
        continue-on-error: true
        run: docker rm ${env:CONTAINER_NAME}-dev

      - name: Run Container
        run: |
          docker run -d -p 8080:8080 --name ${env:CONTAINER_NAME}-dev gem:dev


  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build JAR
        run: |
          docker run --rm -v ${PWD}:/app -w /app maven:3.9.6-eclipse-temurin-21 mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t gem:prod .

      - name: Stop Old Container
        continue-on-error: true
        run: docker stop ${env:CONTAINER_NAME}-prod

      - name: Remove Old Container
        continue-on-error: true
        run: docker rm ${env:CONTAINER_NAME}-prod

      - name: Run Container
        run: |
          docker run -d -p 8081:8080 --name ${env:CONTAINER_NAME}-prod gem:prod